### ISSUE TITLE
Timeout for Authenticate is incorrect because the value is multiplied twice

### ISSUE THREAD

**Issue by dv-user1** [kirves/goradius#5]
On line 55
https://github.com/kirves/goradius/blob/master/goradius.go#L55
a.timeout is multipled by time.second 
==> conn, err := net.DialTimeout("udp", url, a.timeout*time.Second)

but the timeout in seconds was already multiplied by time.second on both line 42 and 48.
https://github.com/kirves/goradius/blob/master/goradius.go#L42
https://github.com/kirves/goradius/blob/master/goradius.go#L48

This results in error: "dial udp: i/o timeout"

Solution:
    remove _\* time.Second_ from **line 55**

**Comment by kirves** [comment]
Fixed, thanks.
